name: Deploy to AWS EC2

on:
  push:
    branches:
      - main  # Jalankan saat ada push ke branch 'main'

jobs:
  deploy:
    runs-on: ubuntu-latest

    permissions:
      id-token: write
      contents: read

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          role-to-assume: ${{ secrets.AWS_ROLE_TO_ASSUME }}
          aws-region: ${{ secrets.AWS_REGION }}

      - name: SSH ke EC2 dan Deploy
        run: |
          ssh -o StrictHostKeyChecking=no ubuntu@your-ec2-ip << 'EOF'
          cd /var/www/dashboard-microthings
          git pull origin main
          npm install
          npm run build
          pm2 restart all
          EOF
